export const defaultOptions = {
    graphic_type: [ "Line Series", "Step Line Series" ],
    logarithm: false,
    curved: false,
    filled: false,
    enabled_color: false,
    limit_max: "",
    limit_min: "",
    color: "",
    pos: ["-1"],
    stroke: [ "Light", "Medium", "Bold", "Bolder" ],
    canvas: [ "Default", "Dotted", "Dashed", "Large Dashed", "Dotted Dashed"],
    decimal: [ "Default", "0.#", "0.##", "0.###", "0.####", "0.#####", "0.######", "0.#######", "0.########" ],
    unit: [ "Default" ],
    prefix: [ "Default" ],
    isEnable: false,
    onlyCollapseValues: false,
    collapseValue: "",
}